### ISSUE TITLE
Hardcode dialogue title

### ISSUE THREAD

**Issue by Vealor** [Vealor/UVic-SENG426#206]
[SendChequeJFrame.java:52](https://github.com/Vealor/UVic-SENG426/blob/c96562723c1c6ed462f6e4fbeb45b489f4313d94/The%20e-Cheque%20Client/src/eCheque/SendChequeJFrame.java#L52)

**Comment by Vealor** [comment]
I can't actually remember what was wrong with this...

**Comment by jordan-heemskerk** [comment]
@Vealor dialog title is a parameter of the method, but is always called as the same value.

**Comment by Vealor** [comment]
@jordan-heemskerk now that I've had more time to look at it, wouldn't it make sense to keep it as-is in case it will be used elsewhere in the future?

**Comment by jordan-heemskerk** [comment]
Ya, if that's a valid use case... Close it!
